import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-explicit-any": "error"
    }
  },
  {
    ignores: [
      "dist",
      "coverage",
      "node_modules",
      // Generated by `pnpm generate`; fix the spec or openapi-ts.config.ts instead.
      "src/gen"
    ]
  }
);
